-- Production proof pack. GENERATED by setup/generate_reporting_ddl.py from
-- cloud_function/report_specs.py. Every query is read-only and has no row cap.
-- Replace PROJECT_ID, BQ_DATASET and AFFECTED_DATE placeholders before execution.

-- ---------------------------------------------------------------------------
-- --manifest
-- Execution identity and incident parameters.
-- ---------------------------------------------------------------------------
SELECT CURRENT_TIMESTAMP() AS captured_at, '${PROJECT_ID}' AS project_id, '${BQ_DATASET}' AS dataset_id, DATE '${AFFECTED_DATE}' AS affected_date, 19 AS reporting_table_count;

-- ---------------------------------------------------------------------------
-- --table_metadata
-- Table types, creation times, row counts and storage bytes visible to this identity.
-- ---------------------------------------------------------------------------
SELECT t.table_name, t.table_type, t.creation_time, s.row_count, s.size_bytes FROM `${PROJECT_ID}.${BQ_DATASET}.INFORMATION_SCHEMA.TABLES` t LEFT JOIN `${PROJECT_ID}.${BQ_DATASET}.__TABLES__` s ON s.table_id = t.table_name ORDER BY t.table_type, t.table_name;

-- ---------------------------------------------------------------------------
-- --column_partitioning_clustering
-- Partition and clustering metadata visible to this identity.
-- ---------------------------------------------------------------------------
SELECT table_name, column_name, data_type, is_nullable, is_partitioning_column, clustering_ordinal_position FROM `${PROJECT_ID}.${BQ_DATASET}.INFORMATION_SCHEMA.COLUMNS` ORDER BY table_name, ordinal_position;

-- ---------------------------------------------------------------------------
-- --reporting_table_counts
-- Counts and date coverage for all registered Reporting tables.
-- ---------------------------------------------------------------------------
SELECT 'reporting_channel_basic_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3`
UNION ALL
SELECT 'reporting_channel_province_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_province_a3`
UNION ALL
SELECT 'reporting_channel_playback_location_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_playback_location_a3`
UNION ALL
SELECT 'reporting_channel_traffic_source_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3`
UNION ALL
SELECT 'reporting_channel_device_os_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3`
UNION ALL
SELECT 'reporting_channel_subtitles_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_subtitles_a3`
UNION ALL
SELECT 'reporting_channel_combined_a3' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_combined_a3`
UNION ALL
SELECT 'reporting_channel_demographics_a1' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_demographics_a1`
UNION ALL
SELECT 'reporting_channel_sharing_service_a1' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_sharing_service_a1`
UNION ALL
SELECT 'reporting_channel_cards_a1' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_cards_a1`
UNION ALL
SELECT 'reporting_channel_end_screens_a1' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_end_screens_a1`
UNION ALL
SELECT 'reporting_channel_reach_basic_a1' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_basic_a1`
UNION ALL
SELECT 'reporting_channel_reach_combined_a1' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_combined_a1`
UNION ALL
SELECT 'reporting_playlist_basic_a2' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_basic_a2`
UNION ALL
SELECT 'reporting_playlist_province_a2' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_province_a2`
UNION ALL
SELECT 'reporting_playlist_playback_location_a2' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_playback_location_a2`
UNION ALL
SELECT 'reporting_playlist_traffic_source_a2' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_traffic_source_a2`
UNION ALL
SELECT 'reporting_playlist_device_os_a2' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_device_os_a2`
UNION ALL
SELECT 'reporting_playlist_combined_a2' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, MAX(report_date) AS latest_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_combined_a2`
ORDER BY table_name;

-- ---------------------------------------------------------------------------
-- --reporting_native_grain_duplicates
-- Every duplicate native-grain group across Reporting.
-- ---------------------------------------------------------------------------
SELECT 'reporting_channel_basic_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_province_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_province_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_playback_location_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_playback_location_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_traffic_source_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_device_os_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_subtitles_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_subtitles_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, subtitle_language, subtitle_language_autotranslated HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_combined_a3' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_combined_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_demographics_a1' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_demographics_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, age_group, gender HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_sharing_service_a1' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_sharing_service_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, sharing_service HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_cards_a1' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_cards_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, card_type, card_id HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_end_screens_a1' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_end_screens_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, end_screen_element_type, end_screen_element_id HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_reach_basic_a1' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_basic_a1` GROUP BY report_date, channel_id, video_id HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_channel_reach_combined_a1' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_combined_a1` GROUP BY report_date, channel_id, video_id, traffic_source_type, traffic_source_detail, operating_system, device_type HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_playlist_basic_a2' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_basic_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_playlist_province_a2' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_province_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_playlist_playback_location_a2' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_playback_location_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_playlist_traffic_source_a2' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_traffic_source_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_playlist_device_os_a2' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_device_os_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system HAVING COUNT(*) > 1) GROUP BY report_date
UNION ALL
SELECT 'reporting_playlist_combined_a2' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM (SELECT report_date FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_combined_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system HAVING COUNT(*) > 1) GROUP BY report_date
ORDER BY table_name, report_date;

-- ---------------------------------------------------------------------------
-- --reporting_multiple_report_ids
-- Partitions containing more than one report id.
-- ---------------------------------------------------------------------------
SELECT 'reporting_channel_basic_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_province_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_province_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_playback_location_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_playback_location_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_traffic_source_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_device_os_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_subtitles_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_subtitles_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_combined_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_combined_a3` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_demographics_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_demographics_a1` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_sharing_service_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_sharing_service_a1` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_cards_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_cards_a1` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_end_screens_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_end_screens_a1` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_reach_basic_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_basic_a1` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_reach_combined_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_combined_a1` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_basic_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_basic_a2` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_province_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_province_a2` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_playback_location_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_playback_location_a2` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_traffic_source_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_traffic_source_a2` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_device_os_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_device_os_a2` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_combined_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_combined_a2` GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1
ORDER BY table_name, report_date;

-- ---------------------------------------------------------------------------
-- --reporting_partition_inventory
-- Complete Reporting partition and ingestion-generation inventory.
-- ---------------------------------------------------------------------------
SELECT 'reporting_channel_basic_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_province_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_province_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_playback_location_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_playback_location_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_traffic_source_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_device_os_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_subtitles_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_subtitles_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_combined_a3' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_combined_a3` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_demographics_a1' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_demographics_a1` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_sharing_service_a1' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_sharing_service_a1` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_cards_a1' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_cards_a1` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_end_screens_a1' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_end_screens_a1` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_reach_basic_a1' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_basic_a1` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_channel_reach_combined_a1' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_combined_a1` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_playlist_basic_a2' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_basic_a2` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_playlist_province_a2' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_province_a2` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_playlist_playback_location_a2' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_playback_location_a2` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_playlist_traffic_source_a2' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_traffic_source_a2` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_playlist_device_os_a2' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_device_os_a2` GROUP BY report_date, report_id, load_source, ingested_at
UNION ALL
SELECT 'reporting_playlist_combined_a2' AS table_name, report_date, report_id, load_source, ingested_at, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_combined_a2` GROUP BY report_date, report_id, load_source, ingested_at
ORDER BY table_name, report_date, report_id, ingested_at;

-- ---------------------------------------------------------------------------
-- --incident_device_rows
-- Every physical row in the affected device partition.
-- ---------------------------------------------------------------------------
SELECT * FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` WHERE report_date = DATE '${AFFECTED_DATE}' ORDER BY video_id, device_type, operating_system, ingested_at;

-- ---------------------------------------------------------------------------
-- --incident_traffic_rows
-- Every physical row in the affected traffic partition.
-- ---------------------------------------------------------------------------
SELECT * FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` WHERE report_date = DATE '${AFFECTED_DATE}' ORDER BY video_id, traffic_source_type, traffic_source_detail, ingested_at;

-- ---------------------------------------------------------------------------
-- --incident_ledger_rows
-- Complete Reporting ledger history.
-- ---------------------------------------------------------------------------
SELECT * FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_ingest_ledger` ORDER BY report_type, report_date, report_create_time, report_id, ingested_at;

-- ---------------------------------------------------------------------------
-- --incident_device_duplicate_rows
-- Every physical duplicate row using the complete channel_device_os_a3 native grain.
-- ---------------------------------------------------------------------------
SELECT *, COUNT(*) OVER (PARTITION BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system) AS copies FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` WHERE report_date = DATE '${AFFECTED_DATE}' QUALIFY copies > 1 ORDER BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system, ingested_at;

-- ---------------------------------------------------------------------------
-- --incident_device_canonical_copies
-- Canonical physical copies and every ingestion timestamp.
-- ---------------------------------------------------------------------------
SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system, engaged_views, views, watch_time_minutes, average_view_duration_seconds, average_view_duration_percentage, red_views, red_watch_time_minutes, report_id, report_create_time, job_id, load_source, COUNT(*) AS physical_copy_count, ARRAY_AGG(ingested_at ORDER BY ingested_at) AS ingestion_timestamps FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` WHERE report_date = DATE '${AFFECTED_DATE}' GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system, engaged_views, views, watch_time_minutes, average_view_duration_seconds, average_view_duration_percentage, red_views, red_watch_time_minutes, report_id, report_create_time, job_id, load_source ORDER BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system;

-- ---------------------------------------------------------------------------
-- --incident_traffic_duplicate_rows
-- Every physical duplicate row using the complete channel_traffic_source_a3 native grain.
-- ---------------------------------------------------------------------------
SELECT *, COUNT(*) OVER (PARTITION BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail) AS copies FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` WHERE report_date = DATE '${AFFECTED_DATE}' QUALIFY copies > 1 ORDER BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail, ingested_at;

-- ---------------------------------------------------------------------------
-- --incident_traffic_canonical_copies
-- Canonical physical copies and every ingestion timestamp.
-- ---------------------------------------------------------------------------
SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail, engaged_views, views, watch_time_minutes, average_view_duration_seconds, average_view_duration_percentage, red_views, red_watch_time_minutes, report_id, report_create_time, job_id, load_source, COUNT(*) AS physical_copy_count, ARRAY_AGG(ingested_at ORDER BY ingested_at) AS ingestion_timestamps FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` WHERE report_date = DATE '${AFFECTED_DATE}' GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail, engaged_views, views, watch_time_minutes, average_view_duration_seconds, average_view_duration_percentage, red_views, red_watch_time_minutes, report_id, report_create_time, job_id, load_source ORDER BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail;

-- ---------------------------------------------------------------------------
-- --ledger_duplicates
-- Every report id with more than one physical ledger row.
-- ---------------------------------------------------------------------------
SELECT report_id, ARRAY_AGG(STRUCT(job_id, report_type, report_date, report_create_time, status, row_count, csv_bytes, content_sha256, gcs_uri, load_source, ingested_at, error) ORDER BY ingested_at) AS ledger_rows, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_ingest_ledger` GROUP BY report_id HAVING COUNT(*) > 1 ORDER BY report_id;

-- ---------------------------------------------------------------------------
-- --loaded_generations
-- Jobs and report dates with more than one loaded generation.
-- ---------------------------------------------------------------------------
SELECT job_id, report_date, ARRAY_AGG(STRUCT(report_id, report_create_time, status, ingested_at) ORDER BY report_create_time, ingested_at) AS generations FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_ingest_ledger` WHERE status = 'loaded' GROUP BY job_id, report_date HAVING COUNT(*) > 1 ORDER BY report_date, job_id;

-- ---------------------------------------------------------------------------
-- --ledger_table_mismatches
-- Loaded ledger counts and physical table counts in both directions.
-- ---------------------------------------------------------------------------
WITH t AS (SELECT 'channel_basic_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_province_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_province_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_playback_location_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_playback_location_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_traffic_source_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_device_os_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_device_os_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_subtitles_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_subtitles_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_combined_a3' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_combined_a3` GROUP BY report_id
UNION ALL
SELECT 'channel_demographics_a1' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_demographics_a1` GROUP BY report_id
UNION ALL
SELECT 'channel_sharing_service_a1' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_sharing_service_a1` GROUP BY report_id
UNION ALL
SELECT 'channel_cards_a1' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_cards_a1` GROUP BY report_id
UNION ALL
SELECT 'channel_end_screens_a1' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_end_screens_a1` GROUP BY report_id
UNION ALL
SELECT 'channel_reach_basic_a1' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_basic_a1` GROUP BY report_id
UNION ALL
SELECT 'channel_reach_combined_a1' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_reach_combined_a1` GROUP BY report_id
UNION ALL
SELECT 'playlist_basic_a2' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_basic_a2` GROUP BY report_id
UNION ALL
SELECT 'playlist_province_a2' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_province_a2` GROUP BY report_id
UNION ALL
SELECT 'playlist_playback_location_a2' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_playback_location_a2` GROUP BY report_id
UNION ALL
SELECT 'playlist_traffic_source_a2' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_traffic_source_a2` GROUP BY report_id
UNION ALL
SELECT 'playlist_device_os_a2' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_device_os_a2` GROUP BY report_id
UNION ALL
SELECT 'playlist_combined_a2' AS report_type, report_id, COUNT(*) AS physical_rows FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_playlist_combined_a2` GROUP BY report_id), l AS (SELECT report_type, report_id, row_count FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_ingest_ledger` WHERE status = 'loaded') SELECT COALESCE(l.report_type, t.report_type) AS report_type, COALESCE(l.report_id, t.report_id) AS report_id, l.row_count AS ledger_rows, t.physical_rows AS table_rows FROM l FULL OUTER JOIN t USING (report_type, report_id) WHERE l.report_id IS NULL OR t.report_id IS NULL OR l.row_count != t.physical_rows ORDER BY report_type, report_id;

-- ---------------------------------------------------------------------------
-- --incident_device_view_rows
-- Every downstream device view row for the affected date.
-- ---------------------------------------------------------------------------
SELECT * FROM `${PROJECT_ID}.${BQ_DATASET}.channel_device_mix_daily` WHERE report_date = DATE '${AFFECTED_DATE}' ORDER BY video_type, device_type;

-- ---------------------------------------------------------------------------
-- --incident_traffic_view_rows
-- Every downstream traffic view row for the affected date.
-- ---------------------------------------------------------------------------
SELECT * FROM `${PROJECT_ID}.${BQ_DATASET}.video_traffic_detail_daily` WHERE report_date = DATE '${AFFECTED_DATE}' ORDER BY video_id, traffic_source_type, traffic_source_detail;

-- ---------------------------------------------------------------------------
-- --pipeline_mutex_objects
-- Current mutex tables or view before and after deployment.
-- ---------------------------------------------------------------------------
SELECT table_name, table_type, creation_time FROM `${PROJECT_ID}.${BQ_DATASET}.INFORMATION_SCHEMA.TABLES` WHERE table_name IN ('pipeline_write_mutex', 'pipeline_write_mutex_analytics', 'pipeline_write_mutex_reporting') ORDER BY table_name;

-- ---------------------------------------------------------------------------
-- --pipeline_mutex
-- Exactly one row must exist for each writer domain after deployment.
-- ---------------------------------------------------------------------------
BEGIN
  IF EXISTS (SELECT 1 FROM `${PROJECT_ID}.${BQ_DATASET}.INFORMATION_SCHEMA.TABLES` WHERE table_name = 'pipeline_write_mutex') THEN
    EXECUTE IMMEDIATE '''
      SELECT mutex_name, COUNT(*) AS rows_for_mutex, MIN(touched_at) AS first_touched_at, MAX(touched_at) AS last_touched_at FROM `${PROJECT_ID}.${BQ_DATASET}.pipeline_write_mutex` GROUP BY mutex_name ORDER BY mutex_name
    ''';
  ELSE
    SELECT 'missing_before_deployment' AS mutex_name, 0 AS rows_for_mutex, CAST(NULL AS TIMESTAMP) AS first_touched_at, CAST(NULL AS TIMESTAMP) AS last_touched_at;
  END IF;
END;

-- ---------------------------------------------------------------------------
-- --analytics_integrity
-- Complete Analytics counts, coverage, fingerprints and native-grain duplicates.
-- ---------------------------------------------------------------------------
SELECT 'video_metadata' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT snapshot_date) AS partitions, MIN(snapshot_date) AS first_date, MAX(snapshot_date) AS latest_date, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS whole_table_fingerprint, (SELECT COUNT(*) FROM (SELECT 1 FROM `${PROJECT_ID}.${BQ_DATASET}.video_metadata` GROUP BY snapshot_date, video_id HAVING COUNT(*) > 1)) AS duplicate_groups FROM `${PROJECT_ID}.${BQ_DATASET}.video_metadata` t
UNION ALL
SELECT 'daily_video_stats' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT snapshot_date) AS partitions, MIN(snapshot_date) AS first_date, MAX(snapshot_date) AS latest_date, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS whole_table_fingerprint, (SELECT COUNT(*) FROM (SELECT 1 FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_stats` GROUP BY snapshot_date, video_id HAVING COUNT(*) > 1)) AS duplicate_groups FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_stats` t
UNION ALL
SELECT 'daily_video_analytics' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT activity_date) AS partitions, MIN(activity_date) AS first_date, MAX(activity_date) AS latest_date, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS whole_table_fingerprint, (SELECT COUNT(*) FROM (SELECT 1 FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics` GROUP BY activity_date, video_id HAVING COUNT(*) > 1)) AS duplicate_groups FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics` t
UNION ALL
SELECT 'daily_traffic_sources' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT activity_date) AS partitions, MIN(activity_date) AS first_date, MAX(activity_date) AS latest_date, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS whole_table_fingerprint, (SELECT COUNT(*) FROM (SELECT 1 FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` GROUP BY activity_date, video_id, traffic_source_type HAVING COUNT(*) > 1)) AS duplicate_groups FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` t
ORDER BY table_name;

-- ---------------------------------------------------------------------------
-- --analytics_partition_fingerprints
-- Every Analytics partition count and order-independent fingerprint.
-- ---------------------------------------------------------------------------
SELECT 'video_metadata' AS table_name, snapshot_date AS partition_date, COUNT(*) AS physical_rows, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS fingerprint FROM `${PROJECT_ID}.${BQ_DATASET}.video_metadata` t GROUP BY snapshot_date
UNION ALL SELECT 'daily_video_stats', snapshot_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_stats` t GROUP BY snapshot_date
UNION ALL SELECT 'daily_video_analytics', activity_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics` t GROUP BY activity_date
UNION ALL SELECT 'daily_traffic_sources', activity_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` t GROUP BY activity_date ORDER BY table_name, partition_date;

-- ---------------------------------------------------------------------------
-- --analytics_multiple_load_sources
-- Every Analytics native grain carrying more than one load source. Only the two activity-date tables have provenance columns.
-- ---------------------------------------------------------------------------
SELECT 'daily_video_analytics' AS table_name, activity_date AS partition_date, video_id, CAST(NULL AS STRING) AS traffic_source_type, ARRAY_AGG(DISTINCT load_source ORDER BY load_source) AS load_sources FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics` GROUP BY activity_date, video_id HAVING COUNT(DISTINCT load_source) > 1
UNION ALL
SELECT 'daily_traffic_sources', activity_date, video_id, traffic_source_type, ARRAY_AGG(DISTINCT load_source ORDER BY load_source) FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` GROUP BY activity_date, video_id, traffic_source_type HAVING COUNT(DISTINCT load_source) > 1 ORDER BY table_name, partition_date, video_id, traffic_source_type;

-- ---------------------------------------------------------------------------
-- --analytics_refresh_archive_reconciliation
-- Every archived refresh generation compared with the current live partition by row count and canonical fingerprint.
-- ---------------------------------------------------------------------------
WITH archive AS (SELECT 'daily_video_analytics' AS table_name, activity_date, refresh_run_id, COUNT(*) AS archive_rows, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING((SELECT AS STRUCT a.* EXCEPT(archived_at, refresh_run_id))))) AS archive_fingerprint FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics_refresh_archive` a GROUP BY activity_date, refresh_run_id UNION ALL SELECT 'daily_traffic_sources', activity_date, refresh_run_id, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING((SELECT AS STRUCT a.* EXCEPT(archived_at, refresh_run_id))))) FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources_refresh_archive` a GROUP BY activity_date, refresh_run_id), live AS (SELECT 'daily_video_analytics' AS table_name, activity_date, COUNT(*) AS live_rows, BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS live_fingerprint FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics` t GROUP BY activity_date UNION ALL SELECT 'daily_traffic_sources', activity_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` t GROUP BY activity_date) SELECT archive.table_name, archive.activity_date, archive.refresh_run_id, archive.archive_rows, live.live_rows, archive.archive_fingerprint, live.live_fingerprint, archive.archive_rows = live.live_rows AS row_count_equal, archive.archive_fingerprint = live.live_fingerprint AS fingerprint_equal FROM archive LEFT JOIN live USING (table_name, activity_date) ORDER BY table_name, activity_date, refresh_run_id;

-- ---------------------------------------------------------------------------
-- --reconcile_views_video_day
-- Every joined video-day across the shared window. Grain: activity date and video id. Threshold: greater of 5 views or 5 percent of Analytics views.
-- ---------------------------------------------------------------------------
WITH rd AS (SELECT DISTINCT report_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3`), ad AS (SELECT DISTINCT activity_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources`), shared AS (SELECT d FROM rd JOIN ad USING (d)), r AS (SELECT report_date AS d, video_id, SUM(views) AS reporting_views, SUM(engaged_views) AS reporting_engaged FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` WHERE report_date IN (SELECT d FROM shared) AND video_id IS NOT NULL GROUP BY d, video_id), a AS (SELECT activity_date AS d, video_id, SUM(views) AS analytics_views FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` WHERE activity_date IN (SELECT d FROM shared) GROUP BY d, video_id HAVING analytics_views > 0) SELECT COALESCE(r.d, a.d) AS activity_date, COALESCE(r.video_id, a.video_id) AS video_id, r.reporting_views, r.reporting_engaged, a.analytics_views, ABS(IFNULL(r.reporting_views, 0) - IFNULL(a.analytics_views, 0)) AS absolute_diff, GREATEST(5, 0.05 * IFNULL(a.analytics_views, 0)) AS allowed_diff, r.d IS NULL AS analytics_only, a.d IS NULL AS reporting_only FROM r FULL OUTER JOIN a USING (d, video_id) ORDER BY activity_date, video_id;

-- ---------------------------------------------------------------------------
-- --reconcile_views_channel_day
-- Every channel-day across the shared date window with both source totals.
-- ---------------------------------------------------------------------------
WITH r AS (SELECT report_date AS d, SUM(views) AS reporting_views, SUM(engaged_views) AS reporting_engaged FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` GROUP BY d), a AS (SELECT activity_date AS d, SUM(views) AS analytics_views FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` GROUP BY d), win AS (SELECT MIN(d) AS lo, MAX(d) AS hi FROM (SELECT d FROM r JOIN a USING (d))) SELECT COALESCE(r.d, a.d) AS activity_date, reporting_views, reporting_engaged, analytics_views, reporting_views - analytics_views AS signed_diff, SAFE_DIVIDE(ABS(reporting_views - analytics_views), analytics_views) AS absolute_diff_share, CASE WHEN r.d IS NULL THEN 'analytics_only' WHEN a.d IS NULL THEN 'reporting_only' END AS one_sided FROM r FULL OUTER JOIN a USING (d), win WHERE COALESCE(r.d, a.d) BETWEEN win.lo AND win.hi ORDER BY activity_date;

-- ---------------------------------------------------------------------------
-- --reconcile_subscribers
-- Every video-day whose subscriber gains differ by more than one across the shared window.
-- ---------------------------------------------------------------------------
WITH shared AS (SELECT d FROM (SELECT DISTINCT report_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3`) JOIN (SELECT DISTINCT activity_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics`) USING (d)), r AS (SELECT report_date AS d, video_id, SUM(subscribers_gained) AS reporting_subscribers FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_basic_a3` WHERE video_id IS NOT NULL AND report_date IN (SELECT d FROM shared) GROUP BY d, video_id), a AS (SELECT activity_date AS d, video_id, SUM(subscribers_gained) AS analytics_subscribers FROM `${PROJECT_ID}.${BQ_DATASET}.daily_video_analytics` WHERE activity_date IN (SELECT d FROM shared) GROUP BY d, video_id) SELECT COALESCE(r.d, a.d) AS activity_date, COALESCE(r.video_id, a.video_id) AS video_id, reporting_subscribers, analytics_subscribers, ABS(IFNULL(reporting_subscribers, 0) - IFNULL(analytics_subscribers, 0)) AS absolute_diff FROM r FULL OUTER JOIN a USING (d, video_id) WHERE ABS(IFNULL(reporting_subscribers, 0) - IFNULL(analytics_subscribers, 0)) > 1 ORDER BY activity_date, video_id;

-- ---------------------------------------------------------------------------
-- --cross_source_date_coverage
-- Every date available in only one traffic source within the shared minimum and maximum window.
-- ---------------------------------------------------------------------------
WITH r AS (SELECT DISTINCT report_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3`), a AS (SELECT DISTINCT activity_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources`), win AS (SELECT MIN(d) AS lo, MAX(d) AS hi FROM (SELECT d FROM r JOIN a USING (d))) SELECT COALESCE(r.d, a.d) AS activity_date, r.d IS NULL AS analytics_only, a.d IS NULL AS reporting_only FROM r FULL OUTER JOIN a USING (d), win WHERE COALESCE(r.d, a.d) BETWEEN win.lo AND win.hi AND (r.d IS NULL OR a.d IS NULL) ORDER BY activity_date;

-- ---------------------------------------------------------------------------
-- --analytics_partial_days
-- Every shared date with Reporting video rows absent from Analytics traffic. Denominator is Reporting videos with positive views.
-- ---------------------------------------------------------------------------
WITH shared AS (SELECT d FROM (SELECT DISTINCT report_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3`) JOIN (SELECT DISTINCT activity_date AS d FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources`) USING (d)), r AS (SELECT report_date AS d, video_id, SUM(views) AS views FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3` WHERE video_id IS NOT NULL AND report_date IN (SELECT d FROM shared) GROUP BY d, video_id HAVING views > 0), a AS (SELECT DISTINCT activity_date AS d, video_id FROM `${PROJECT_ID}.${BQ_DATASET}.daily_traffic_sources` WHERE activity_date IN (SELECT d FROM shared)) SELECT r.d AS activity_date, COUNT(*) AS reporting_videos_missing, SUM(r.views) AS reporting_views_missing, (SELECT COUNT(*) FROM r denominator WHERE denominator.d = r.d) AS reporting_positive_view_videos FROM r LEFT JOIN a USING (d, video_id) WHERE a.video_id IS NULL GROUP BY activity_date ORDER BY activity_date;

-- ---------------------------------------------------------------------------
-- --reporting_coverage_calendar
-- Complete ledger coverage by report type and date, including every status and generation.
-- ---------------------------------------------------------------------------
SELECT report_type, report_date, ARRAY_AGG(STRUCT(report_id, report_create_time, status, row_count, load_source, ingested_at, error) ORDER BY report_create_time, ingested_at) AS generations FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_ingest_ledger` GROUP BY report_type, report_date ORDER BY report_type, report_date;

-- ---------------------------------------------------------------------------
-- --reporting_generation_latency
-- Generation latency in hours and regeneration counts for every report type.
-- ---------------------------------------------------------------------------
SELECT report_type, APPROX_QUANTILES(TIMESTAMP_DIFF(report_create_time, TIMESTAMP(report_date, 'America/Los_Angeles'), HOUR), 4) AS hours_quartiles, COUNT(DISTINCT report_date) AS days, COUNT(*) AS reports, COUNT(DISTINCT IF(generations > 1, report_date, NULL)) AS regenerated_days FROM (SELECT *, COUNT(*) OVER (PARTITION BY job_id, report_date) AS generations FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_ingest_ledger`) GROUP BY report_type ORDER BY report_type;

-- ---------------------------------------------------------------------------
-- --traffic_anonymization
-- Traffic detail null and anonymization shares. Denominator is every physical traffic row.
-- ---------------------------------------------------------------------------
SELECT COUNT(*) AS denominator_rows, COUNTIF(video_id IS NULL) AS video_id_null_rows, SAFE_DIVIDE(COUNTIF(video_id IS NULL), COUNT(*)) AS video_id_null_share, COUNTIF(traffic_source_detail IS NULL) AS detail_null_rows, SAFE_DIVIDE(COUNTIF(traffic_source_detail IS NULL), COUNT(*)) AS detail_null_share, COUNTIF(country_code = 'ZZ') AS country_zz_rows, SAFE_DIVIDE(COUNTIF(country_code = 'ZZ'), COUNT(*)) AS country_zz_share FROM `${PROJECT_ID}.${BQ_DATASET}.reporting_channel_traffic_source_a3`;
