-- Structural checks for EVERY Reporting API raw table. GENERATED by
-- setup/generate_reporting_ddl.py from cloud_function/report_specs.py; do not edit by hand.
-- Three tagged blocks; each is expected to return 0 rows. Replace `youtube_analytics.` with
-- the dataset under test. scripts/verify_reporting.sh runs all three.

-- ---------------------------------------------------------------------------
-- --grain_unique_all
-- Expected: 0 rows. A row is a (table, report_date) with duplicate grain keys.
-- ---------------------------------------------------------------------------
SELECT 'reporting_channel_basic_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code FROM `youtube_analytics.reporting_channel_basic_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_province_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code FROM `youtube_analytics.reporting_channel_province_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_playback_location_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail FROM `youtube_analytics.reporting_channel_playback_location_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_traffic_source_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail FROM `youtube_analytics.reporting_channel_traffic_source_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_device_os_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system FROM `youtube_analytics.reporting_channel_device_os_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_subtitles_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, subtitle_language, subtitle_language_autotranslated FROM `youtube_analytics.reporting_channel_subtitles_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, subtitle_language, subtitle_language_autotranslated HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_combined_a3' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system FROM `youtube_analytics.reporting_channel_combined_a3` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_demographics_a1' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, age_group, gender FROM `youtube_analytics.reporting_channel_demographics_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, age_group, gender HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_sharing_service_a1' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, sharing_service FROM `youtube_analytics.reporting_channel_sharing_service_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, sharing_service HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_cards_a1' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, card_type, card_id FROM `youtube_analytics.reporting_channel_cards_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, card_type, card_id HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_end_screens_a1' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, end_screen_element_type, end_screen_element_id FROM `youtube_analytics.reporting_channel_end_screens_a1` GROUP BY report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, end_screen_element_type, end_screen_element_id HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_reach_basic_a1' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id FROM `youtube_analytics.reporting_channel_reach_basic_a1` GROUP BY report_date, channel_id, video_id HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_channel_reach_combined_a1' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, video_id, traffic_source_type, traffic_source_detail, operating_system, device_type FROM `youtube_analytics.reporting_channel_reach_combined_a1` GROUP BY report_date, channel_id, video_id, traffic_source_type, traffic_source_detail, operating_system, device_type HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_playlist_basic_a2' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code FROM `youtube_analytics.reporting_playlist_basic_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_playlist_province_a2' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code FROM `youtube_analytics.reporting_playlist_province_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_playlist_playback_location_a2' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail FROM `youtube_analytics.reporting_playlist_playback_location_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_playlist_traffic_source_a2' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail FROM `youtube_analytics.reporting_playlist_traffic_source_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_playlist_device_os_a2' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system FROM `youtube_analytics.reporting_playlist_device_os_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system HAVING COUNT(*) > 1)
GROUP BY 1, 2
UNION ALL
SELECT 'reporting_playlist_combined_a2' AS table_name, report_date, COUNT(*) AS dup_groups FROM (
  SELECT report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system FROM `youtube_analytics.reporting_playlist_combined_a2` GROUP BY report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system HAVING COUNT(*) > 1)
GROUP BY 1, 2
ORDER BY 1, 2;

-- ---------------------------------------------------------------------------
-- --one_report_per_day_all
-- Expected: 0 rows. Every partition holds exactly one report_id.
-- ---------------------------------------------------------------------------
SELECT 'reporting_channel_basic_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_basic_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_province_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_province_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_playback_location_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_playback_location_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_traffic_source_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_traffic_source_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_device_os_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_device_os_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_subtitles_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_subtitles_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_combined_a3' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_combined_a3` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_demographics_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_demographics_a1` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_sharing_service_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_sharing_service_a1` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_cards_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_cards_a1` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_end_screens_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_end_screens_a1` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_reach_basic_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_reach_basic_a1` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_channel_reach_combined_a1' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_channel_reach_combined_a1` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_basic_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_playlist_basic_a2` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_province_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_playlist_province_a2` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_playback_location_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_playlist_playback_location_a2` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_traffic_source_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_playlist_traffic_source_a2` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_device_os_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_playlist_device_os_a2` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
UNION ALL
SELECT 'reporting_playlist_combined_a2' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids
FROM `youtube_analytics.reporting_playlist_combined_a2` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1
ORDER BY 1, 2;

-- ---------------------------------------------------------------------------
-- --ledger_matches_tables_all
-- Expected: 0 rows. Both directions: every ledger row with status loaded has exactly its
-- row_count rows in its table, and every report_id present in a table is loaded in the ledger.
-- ---------------------------------------------------------------------------
WITH t AS (
  SELECT 'channel_basic_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_basic_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_province_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_province_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_playback_location_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_playback_location_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_traffic_source_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_traffic_source_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_device_os_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_device_os_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_subtitles_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_subtitles_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_combined_a3' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_combined_a3` GROUP BY 1, 2
  UNION ALL SELECT 'channel_demographics_a1' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_demographics_a1` GROUP BY 1, 2
  UNION ALL SELECT 'channel_sharing_service_a1' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_sharing_service_a1` GROUP BY 1, 2
  UNION ALL SELECT 'channel_cards_a1' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_cards_a1` GROUP BY 1, 2
  UNION ALL SELECT 'channel_end_screens_a1' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_end_screens_a1` GROUP BY 1, 2
  UNION ALL SELECT 'channel_reach_basic_a1' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_reach_basic_a1` GROUP BY 1, 2
  UNION ALL SELECT 'channel_reach_combined_a1' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_channel_reach_combined_a1` GROUP BY 1, 2
  UNION ALL SELECT 'playlist_basic_a2' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_playlist_basic_a2` GROUP BY 1, 2
  UNION ALL SELECT 'playlist_province_a2' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_playlist_province_a2` GROUP BY 1, 2
  UNION ALL SELECT 'playlist_playback_location_a2' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_playlist_playback_location_a2` GROUP BY 1, 2
  UNION ALL SELECT 'playlist_traffic_source_a2' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_playlist_traffic_source_a2` GROUP BY 1, 2
  UNION ALL SELECT 'playlist_device_os_a2' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_playlist_device_os_a2` GROUP BY 1, 2
  UNION ALL SELECT 'playlist_combined_a2' AS report_type, report_id, COUNT(*) AS n FROM `youtube_analytics.reporting_playlist_combined_a2` GROUP BY 1, 2
),
l AS (SELECT report_type, report_id, row_count FROM `youtube_analytics.reporting_ingest_ledger` WHERE status = 'loaded')
SELECT COALESCE(l.report_type, t.report_type) AS report_type, COALESCE(l.report_id, t.report_id) AS report_id,
       l.row_count AS ledger_rows, t.n AS table_rows,
       CASE WHEN l.report_id IS NULL THEN 'in_table_not_loaded_in_ledger'
            WHEN t.report_id IS NULL THEN 'loaded_in_ledger_missing_from_table' ELSE 'row_count_differs' END AS problem
FROM l FULL OUTER JOIN t USING (report_type, report_id)
WHERE l.report_id IS NULL OR t.report_id IS NULL OR l.row_count != t.n
ORDER BY 1, 2;
