#!/usr/bin/env python3
"""Render sql/reporting_tables.sql and sql/verification/reporting_structural_checks.sql from
cloud_function/report_specs.py.

The DDL is generated, committed, and asserted equal to this generator's output by
tests/test_report_specs.py, so the schema in code and the schema in SQL cannot drift.

    python3 setup/generate_reporting_ddl.py            # writes sql/reporting_tables.sql
    python3 setup/generate_reporting_ddl.py --check    # exit 1 if the committed file differs

Like sql/create_tables.sql the output carries ${BQ_DATASET} placeholders; apply it with
    sed "s/\\${BQ_DATASET}/youtube_analytics_staging/g" sql/reporting_tables.sql | bq query --use_legacy_sql=false
"""

import argparse
import sys
from pathlib import Path

import _bootstrap  # noqa: F401  (adds cloud_function/ to sys.path)

# isort: split   (everything below needs _bootstrap to have run first)
from report_specs import LEDGER_TABLE, PROVENANCE_COLUMNS, SPECS

OUT = _bootstrap.REPO_ROOT / "sql" / "reporting_tables.sql"
CHECKS_OUT = _bootstrap.REPO_ROOT / "sql" / "verification" / "reporting_structural_checks.sql"

HEADER = """-- YouTube Reporting API raw tables. GENERATED by setup/generate_reporting_ddl.py from
-- cloud_function/report_specs.py. Do not edit by hand; edit the specs and re-run.
--
-- One table per report type at the report's native grain (one row per combination of
-- its dimensions per Pacific day). Dimension values can be NULL: channel_basic_a3 emits a
-- channel-level row with no video_id, and detail dimensions are blank under YouTube's
-- anonymisation threshold. report_date is the report day; the idempotency key is the
-- whole report_date partition, replaced atomically when a newer generation of the same
-- day arrives. Provenance columns say which report file each row came from.
--
-- Ratios (ctr, *_rate, *_percentage) are per-row averages and are never summed; recompute
-- from totals. Timezone: report_date is a Pacific-time day, the same convention as the
-- Analytics API's activity_date.

"""

LEDGER_DDL = f"""-- One row per report file YouTube has generated. Every status transition is a MERGE
-- keyed on report_id. status: loaded | header_only | header_only_conflict | superseded |
-- skipped_older | failed. gcs_uri points at the archived copy; content_sha256 is the
-- CSV body's hash before compression.
CREATE TABLE IF NOT EXISTS `${{BQ_DATASET}}.{LEDGER_TABLE}` (
    report_id STRING NOT NULL,
    job_id STRING NOT NULL,
    report_type STRING NOT NULL,
    report_date DATE NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    status STRING NOT NULL,
    row_count INT64,
    csv_bytes INT64,
    content_sha256 STRING,
    gcs_uri STRING,
    load_source STRING,
    ingested_at TIMESTAMP NOT NULL,
    error STRING
)
CLUSTER BY job_id, report_date
OPTIONS (
    description = 'Ingest ledger for YouTube Reporting API report files. One row per report_id; drives what to load and proves newest-createTime-wins.'
);
"""


def render() -> str:
    parts = [HEADER, LEDGER_DDL]
    for spec in SPECS.values():
        cols = []
        for c in spec.grain_columns:
            # Only the day and the channel are guaranteed. channel_basic_a3 emits a row with an
            # empty video_id for channel-level activity (observed 2026-09-03), and detail
            # dimensions are blank below YouTube's anonymisation threshold.
            required = " NOT NULL" if c in ("report_date", "channel_id") else ""
            cols.append(f"    {c} {spec.column_type(c)}{required}")
        for m in spec.metrics:
            cols.append(f"    {m} {spec.column_type(m)}")
        for name, typ, required in PROVENANCE_COLUMNS:
            cols.append(f"    {name} {typ}{' NOT NULL' if required else ''}")
        grain = ", ".join(spec.grain_columns)
        parts.append(
            f"-- {spec.report_type}: grain ({grain})\n"
            f"CREATE TABLE IF NOT EXISTS `${{BQ_DATASET}}.{spec.table}` (\n"
            + ",\n".join(cols)
            + "\n)\nPARTITION BY report_date\nCLUSTER BY video_id\n"
            f"OPTIONS (\n    description = 'Raw YouTube Reporting API {spec.report_type}. Grain: {grain}. "
            f"Partition = report_date (Pacific day); one report_id per partition.'\n);\n"
        )
    return "\n".join(parts)


CHECKS_HEADER = """-- Structural checks for EVERY Reporting API raw table. GENERATED by
-- setup/generate_reporting_ddl.py from cloud_function/report_specs.py; do not edit by hand.
-- Three tagged blocks; each is expected to return 0 rows. Replace `youtube_analytics.` with
-- the dataset under test. scripts/verify_reporting.sh runs all three.

"""


def render_checks() -> str:
    grain_parts, one_parts, ledger_parts = [], [], []
    for spec in SPECS.values():
        grain = ", ".join(spec.grain_columns)
        grain_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, COUNT(*) AS dup_groups FROM (\n"
            f"  SELECT {grain} FROM `${{BQ_DATASET}}.{spec.table}` GROUP BY {grain} HAVING COUNT(*) > 1)\n"
            f"GROUP BY 1, 2"
        )
        one_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids\n"
            f"FROM `${{BQ_DATASET}}.{spec.table}` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1"
        )
        ledger_parts.append(
            f"SELECT '{spec.report_type}' AS report_type, report_id, COUNT(*) AS n FROM `${{BQ_DATASET}}.{spec.table}` GROUP BY 1, 2"
        )
    table_counts = "\n  UNION ALL ".join(ledger_parts)
    return (
        CHECKS_HEADER
        + "-- ---------------------------------------------------------------------------\n"
        + "-- --grain_unique_all\n-- Expected: 0 rows. A row is a (table, report_date) with duplicate grain keys.\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "\nUNION ALL\n".join(grain_parts) + "\nORDER BY 1, 2;\n\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "-- --one_report_per_day_all\n-- Expected: 0 rows. Every partition holds exactly one report_id.\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "\nUNION ALL\n".join(one_parts) + "\nORDER BY 1, 2;\n\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "-- --ledger_matches_tables_all\n"
        + "-- Expected: 0 rows. Both directions: every ledger row with status loaded has exactly its\n"
        + "-- row_count rows in its table, and every report_id present in a table is loaded in the ledger.\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "WITH t AS (\n  " + table_counts + "\n),\n"
        + "l AS (SELECT report_type, report_id, row_count FROM `${BQ_DATASET}.reporting_ingest_ledger` WHERE status = 'loaded')\n"
        + "SELECT COALESCE(l.report_type, t.report_type) AS report_type, COALESCE(l.report_id, t.report_id) AS report_id,\n"
        + "       l.row_count AS ledger_rows, t.n AS table_rows,\n"
        + "       CASE WHEN l.report_id IS NULL THEN 'in_table_not_loaded_in_ledger'\n"
        + "            WHEN t.report_id IS NULL THEN 'loaded_in_ledger_missing_from_table' ELSE 'row_count_differs' END AS problem\n"
        + "FROM l FULL OUTER JOIN t USING (report_type, report_id)\n"
        + "WHERE l.report_id IS NULL OR t.report_id IS NULL OR l.row_count != t.n\n"
        + "ORDER BY 1, 2;\n"
    ).replace("${BQ_DATASET}", "youtube_analytics")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text, checks = render(), render_checks()
    if args.check:
        stale = [str(f) for f, want in ((OUT, text), (CHECKS_OUT, checks)) if (f.read_text() if f.exists() else "") != want]
        if stale:
            print(f"out of date: {', '.join(stale)}; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print("DDL and structural checks match specs")
        return 0
    OUT.write_text(text)
    CHECKS_OUT.write_text(checks)
    print(f"wrote {OUT} ({len(SPECS)} tables + ledger) and {CHECKS_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
