#!/usr/bin/env python3
"""Render sql/reporting_tables.sql and sql/verification/reporting_structural_checks.sql from
cloud_function/report_specs.py.

The DDL is generated, committed, and asserted equal to this generator's output by
tests/test_report_specs.py, so the schema in code and the schema in SQL cannot drift.

    python3 setup/generate_reporting_ddl.py            # writes sql/reporting_tables.sql
    python3 setup/generate_reporting_ddl.py --check    # exit 1 if the committed file differs

Like sql/create_tables.sql the output carries ${BQ_DATASET} placeholders; apply it with
    sed "s/\\${BQ_DATASET}/youtube_analytics_staging/g" sql/reporting_tables.sql | bq query --use_legacy_sql=false
"""

import argparse
import sys
from pathlib import Path

import _bootstrap  # noqa: F401  (adds cloud_function/ to sys.path)

# isort: split   (everything below needs _bootstrap to have run first)
from report_specs import LEDGER_TABLE, PROVENANCE_COLUMNS, SPECS

OUT = _bootstrap.REPO_ROOT / "sql" / "reporting_tables.sql"
CHECKS_OUT = _bootstrap.REPO_ROOT / "sql" / "verification" / "reporting_structural_checks.sql"
PROOF_OUT = _bootstrap.REPO_ROOT / "sql" / "verification" / "production_proof.sql"

HEADER = """-- YouTube Reporting API raw tables. GENERATED by setup/generate_reporting_ddl.py from
-- cloud_function/report_specs.py. Do not edit by hand; edit the specs and re-run.
--
-- One table per report type at the report's native grain (one row per combination of
-- its dimensions per Pacific day). Dimension values can be NULL: channel_basic_a3 emits a
-- channel-level row with no video_id, and detail dimensions are blank under YouTube's
-- anonymisation threshold. report_date is the report day; the idempotency key is the
-- whole report_date partition, replaced atomically when a newer generation of the same
-- day arrives. Provenance columns say which report file each row came from.
--
-- Ratios (ctr, *_rate, *_percentage) are per-row averages and are never summed; recompute
-- from totals. Timezone: report_date is a Pacific-time day, the same convention as the
-- Analytics API's activity_date.

"""

LEDGER_DDL = f"""-- One row per report file YouTube has generated. Every status transition is a MERGE
-- keyed on report_id. status: loaded | header_only | header_only_conflict | superseded |
-- skipped_older | failed. gcs_uri points at the archived copy; content_sha256 is the
-- CSV body's hash before compression.
CREATE TABLE IF NOT EXISTS `${{BQ_DATASET}}.{LEDGER_TABLE}` (
    report_id STRING NOT NULL,
    job_id STRING NOT NULL,
    report_type STRING NOT NULL,
    report_date DATE NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    status STRING NOT NULL,
    row_count INT64,
    csv_bytes INT64,
    content_sha256 STRING,
    gcs_uri STRING,
    load_source STRING,
    ingested_at TIMESTAMP NOT NULL,
    error STRING
)
CLUSTER BY job_id, report_date
OPTIONS (
    description = 'Ingest ledger for YouTube Reporting API report files. One row per report_id; drives what to load and proves newest-createTime-wins.'
);
"""


def render() -> str:
    parts = [HEADER, LEDGER_DDL]
    for spec in SPECS.values():
        cols = []
        for c in spec.grain_columns:
            # Only the day and the channel are guaranteed. channel_basic_a3 emits a row with an
            # empty video_id for channel-level activity (observed 2026-09-03), and detail
            # dimensions are blank below YouTube's anonymisation threshold.
            required = " NOT NULL" if c in ("report_date", "channel_id") else ""
            cols.append(f"    {c} {spec.column_type(c)}{required}")
        for m in spec.metrics:
            cols.append(f"    {m} {spec.column_type(m)}")
        for name, typ, required in PROVENANCE_COLUMNS:
            cols.append(f"    {name} {typ}{' NOT NULL' if required else ''}")
        grain = ", ".join(spec.grain_columns)
        parts.append(
            f"-- {spec.report_type}: grain ({grain})\n"
            f"CREATE TABLE IF NOT EXISTS `${{BQ_DATASET}}.{spec.table}` (\n"
            + ",\n".join(cols)
            + "\n)\nPARTITION BY report_date\nCLUSTER BY video_id\n"
            f"OPTIONS (\n    description = 'Raw YouTube Reporting API {spec.report_type}. Grain: {grain}. "
            f"Partition = report_date (Pacific day); one report_id per partition.'\n);\n"
        )
    return "\n".join(parts)


CHECKS_HEADER = """-- Structural checks for EVERY Reporting API raw table. GENERATED by
-- setup/generate_reporting_ddl.py from cloud_function/report_specs.py; do not edit by hand.
-- Three tagged blocks; each is expected to return 0 rows. Replace `youtube_analytics.` with
-- the dataset under test. scripts/verify_reporting.sh runs all three.

"""


def render_checks() -> str:
    grain_parts, one_parts, ledger_parts = [], [], []
    for spec in SPECS.values():
        grain = ", ".join(spec.grain_columns)
        grain_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, COUNT(*) AS dup_groups FROM (\n"
            f"  SELECT {grain} FROM `${{BQ_DATASET}}.{spec.table}` GROUP BY {grain} HAVING COUNT(*) > 1)\n"
            f"GROUP BY 1, 2"
        )
        one_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids\n"
            f"FROM `${{BQ_DATASET}}.{spec.table}` GROUP BY 1, 2 HAVING COUNT(DISTINCT report_id) > 1"
        )
        ledger_parts.append(
            f"SELECT '{spec.report_type}' AS report_type, report_id, COUNT(*) AS n FROM `${{BQ_DATASET}}.{spec.table}` GROUP BY 1, 2"
        )
    table_counts = "\n  UNION ALL ".join(ledger_parts)
    return (
        CHECKS_HEADER
        + "-- ---------------------------------------------------------------------------\n"
        + "-- --grain_unique_all\n-- Expected: 0 rows. A row is a (table, report_date) with duplicate grain keys.\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "\nUNION ALL\n".join(grain_parts) + "\nORDER BY 1, 2;\n\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "-- --one_report_per_day_all\n-- Expected: 0 rows. Every partition holds exactly one report_id.\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "\nUNION ALL\n".join(one_parts) + "\nORDER BY 1, 2;\n\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "-- --ledger_matches_tables_all\n"
        + "-- Expected: 0 rows. Both directions: every ledger row with status loaded has exactly its\n"
        + "-- row_count rows in its table, and every report_id present in a table is loaded in the ledger.\n"
        + "-- ---------------------------------------------------------------------------\n"
        + "WITH t AS (\n  " + table_counts + "\n),\n"
        + "l AS (SELECT report_type, report_id, row_count FROM `${BQ_DATASET}.reporting_ingest_ledger` WHERE status = 'loaded')\n"
        + "SELECT COALESCE(l.report_type, t.report_type) AS report_type, COALESCE(l.report_id, t.report_id) AS report_id,\n"
        + "       l.row_count AS ledger_rows, t.n AS table_rows,\n"
        + "       CASE WHEN l.report_id IS NULL THEN 'in_table_not_loaded_in_ledger'\n"
        + "            WHEN t.report_id IS NULL THEN 'loaded_in_ledger_missing_from_table' ELSE 'row_count_differs' END AS problem\n"
        + "FROM l FULL OUTER JOIN t USING (report_type, report_id)\n"
        + "WHERE l.report_id IS NULL OR t.report_id IS NULL OR l.row_count != t.n\n"
        + "ORDER BY 1, 2;\n"
    ).replace("${BQ_DATASET}", "youtube_analytics")


def _proof_block(name: str, description: str, sql: str) -> str:
    return (
        "-- ---------------------------------------------------------------------------\n"
        f"-- --{name}\n"
        f"-- {description}\n"
        "-- ---------------------------------------------------------------------------\n"
        f"{sql.strip()}\n\n"
    )


def render_proof() -> str:
    """Render read-only, unbounded evidence queries from the live schema registry."""
    fq = "`${PROJECT_ID}.${BQ_DATASET}"
    blocks = [
        _proof_block(
            "manifest",
            "Execution identity and incident parameters.",
            "SELECT CURRENT_TIMESTAMP() AS captured_at, '${PROJECT_ID}' AS project_id, "
            "'${BQ_DATASET}' AS dataset_id, DATE '${AFFECTED_DATE}' AS affected_date, "
            f"{len(SPECS)} AS reporting_table_count;",
        ),
        _proof_block(
            "table_metadata",
            "Table types, creation times, row counts and storage bytes visible to this identity.",
            f"SELECT t.table_name, t.table_type, t.creation_time, s.row_count, s.size_bytes "
            f"FROM {fq}.INFORMATION_SCHEMA.TABLES` t LEFT JOIN {fq}.__TABLES__` s "
            "ON s.table_id = t.table_name ORDER BY t.table_type, t.table_name;",
        ),
        _proof_block(
            "column_partitioning_clustering",
            "Partition and clustering metadata visible to this identity.",
            f"SELECT table_name, column_name, data_type, is_nullable, is_partitioning_column, clustering_ordinal_position "
            f"FROM {fq}.INFORMATION_SCHEMA.COLUMNS` ORDER BY table_name, ordinal_position;",
        ),
    ]

    count_parts = []
    duplicate_parts = []
    report_parts = []
    inventory_parts = []
    table_count_parts = []
    for spec in SPECS.values():
        table = f"{fq}.{spec.table}`"
        grain = ", ".join(spec.grain_columns)
        count_parts.append(
            f"SELECT '{spec.table}' AS table_name, COUNT(*) AS physical_rows, "
            f"COUNT(DISTINCT report_date) AS partitions, MIN(report_date) AS first_date, "
            f"MAX(report_date) AS latest_date FROM {table}"
        )
        duplicate_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, COUNT(*) AS duplicate_groups FROM ("
            f"SELECT report_date FROM {table} GROUP BY {grain} HAVING COUNT(*) > 1) GROUP BY report_date"
        )
        report_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, COUNT(DISTINCT report_id) AS report_ids "
            f"FROM {table} GROUP BY report_date HAVING COUNT(DISTINCT report_id) > 1"
        )
        inventory_parts.append(
            f"SELECT '{spec.table}' AS table_name, report_date, report_id, load_source, ingested_at, "
            f"COUNT(*) AS physical_rows FROM {table} GROUP BY report_date, report_id, load_source, ingested_at"
        )
        table_count_parts.append(
            f"SELECT '{spec.report_type}' AS report_type, report_id, COUNT(*) AS physical_rows "
            f"FROM {table} GROUP BY report_id"
        )

    blocks.extend([
        _proof_block("reporting_table_counts", "Counts and date coverage for all registered Reporting tables.",
                     "\nUNION ALL\n".join(count_parts) + "\nORDER BY table_name;"),
        _proof_block("reporting_native_grain_duplicates", "Every duplicate native-grain group across Reporting.",
                     "\nUNION ALL\n".join(duplicate_parts) + "\nORDER BY table_name, report_date;"),
        _proof_block("reporting_multiple_report_ids", "Partitions containing more than one report id.",
                     "\nUNION ALL\n".join(report_parts) + "\nORDER BY table_name, report_date;"),
        _proof_block("reporting_partition_inventory", "Complete Reporting partition and ingestion-generation inventory.",
                     "\nUNION ALL\n".join(inventory_parts) + "\nORDER BY table_name, report_date, report_id, ingested_at;"),
        _proof_block(
            "incident_device_rows", "Every physical row in the affected device partition.",
            f"SELECT * FROM {fq}.reporting_channel_device_os_a3` WHERE report_date = DATE '${{AFFECTED_DATE}}' "
            "ORDER BY video_id, device_type, operating_system, ingested_at;",
        ),
        _proof_block(
            "incident_traffic_rows", "Every physical row in the affected traffic partition.",
            f"SELECT * FROM {fq}.reporting_channel_traffic_source_a3` WHERE report_date = DATE '${{AFFECTED_DATE}}' "
            "ORDER BY video_id, traffic_source_type, traffic_source_detail, ingested_at;",
        ),
        _proof_block(
            "incident_ledger_rows", "Complete Reporting ledger history.",
            f"SELECT * FROM {fq}.{LEDGER_TABLE}` ORDER BY report_type, report_date, report_create_time, report_id, ingested_at;",
        ),
    ])

    for name, report_type in (("device", "channel_device_os_a3"), ("traffic", "channel_traffic_source_a3")):
        spec = SPECS[report_type]
        table = f"{fq}.{spec.table}`"
        grain = ", ".join(spec.grain_columns)
        blocks.append(_proof_block(
            f"incident_{name}_duplicate_rows",
            f"Every physical duplicate row using the complete {report_type} native grain.",
            f"SELECT *, COUNT(*) OVER (PARTITION BY {grain}) AS copies FROM {table} "
            f"WHERE report_date = DATE '${{AFFECTED_DATE}}' QUALIFY copies > 1 ORDER BY {grain}, ingested_at;",
        ))
        canonical = spec.columns + tuple(column for column, _, _ in PROVENANCE_COLUMNS if column != "ingested_at")
        canonical_text = ", ".join(canonical)
        blocks.append(_proof_block(
            f"incident_{name}_canonical_copies",
            "Canonical physical copies and every ingestion timestamp.",
            f"SELECT {canonical_text}, COUNT(*) AS physical_copy_count, ARRAY_AGG(ingested_at ORDER BY ingested_at) "
            f"AS ingestion_timestamps FROM {table} WHERE report_date = DATE '${{AFFECTED_DATE}}' "
            f"GROUP BY {canonical_text} ORDER BY {grain};",
        ))

    table_counts = "\nUNION ALL\n".join(table_count_parts)
    blocks.extend([
        _proof_block(
            "ledger_duplicates", "Every report id with more than one physical ledger row.",
            f"SELECT report_id, ARRAY_AGG(STRUCT(job_id, report_type, report_date, report_create_time, status, row_count, "
            f"csv_bytes, content_sha256, gcs_uri, load_source, ingested_at, error) ORDER BY ingested_at) AS ledger_rows, "
            f"COUNT(*) AS physical_rows FROM {fq}.{LEDGER_TABLE}` GROUP BY report_id HAVING COUNT(*) > 1 ORDER BY report_id;",
        ),
        _proof_block(
            "loaded_generations", "Jobs and report dates with more than one loaded generation.",
            f"SELECT job_id, report_date, ARRAY_AGG(STRUCT(report_id, report_create_time, status, ingested_at) "
            f"ORDER BY report_create_time, ingested_at) AS generations FROM {fq}.{LEDGER_TABLE}` "
            "WHERE status = 'loaded' GROUP BY job_id, report_date HAVING COUNT(*) > 1 ORDER BY report_date, job_id;",
        ),
        _proof_block(
            "ledger_table_mismatches", "Loaded ledger counts and physical table counts in both directions.",
            f"WITH t AS ({table_counts}), l AS (SELECT report_type, report_id, row_count FROM {fq}.{LEDGER_TABLE}` "
            "WHERE status = 'loaded') SELECT COALESCE(l.report_type, t.report_type) AS report_type, "
            "COALESCE(l.report_id, t.report_id) AS report_id, l.row_count AS ledger_rows, t.physical_rows AS table_rows "
            "FROM l FULL OUTER JOIN t USING (report_type, report_id) WHERE l.report_id IS NULL OR t.report_id IS NULL "
            "OR l.row_count != t.physical_rows ORDER BY report_type, report_id;",
        ),
        _proof_block(
            "incident_device_view_rows", "Every downstream device view row for the affected date.",
            f"SELECT * FROM {fq}.channel_device_mix_daily` WHERE report_date = DATE '${{AFFECTED_DATE}}' "
            "ORDER BY video_type, device_type;",
        ),
        _proof_block(
            "incident_traffic_view_rows", "Every downstream traffic view row for the affected date.",
            f"SELECT * FROM {fq}.video_traffic_detail_daily` WHERE report_date = DATE '${{AFFECTED_DATE}}' "
            "ORDER BY video_id, traffic_source_type, traffic_source_detail;",
        ),
        _proof_block(
            "pipeline_mutex_objects", "Current mutex tables or view before and after deployment.",
            f"SELECT table_name, table_type, creation_time FROM {fq}.INFORMATION_SCHEMA.TABLES` "
            "WHERE table_name IN ('pipeline_write_mutex', 'pipeline_write_mutex_analytics', "
            "'pipeline_write_mutex_reporting') ORDER BY table_name;",
        ),
        _proof_block(
            "pipeline_mutex", "Exactly one row must exist for each writer domain after deployment.",
            "BEGIN\n"
            f"  IF EXISTS (SELECT 1 FROM {fq}.INFORMATION_SCHEMA.TABLES` "
            "WHERE table_name = 'pipeline_write_mutex') THEN\n"
            "    EXECUTE IMMEDIATE '''\n"
            f"      SELECT mutex_name, COUNT(*) AS rows_for_mutex, MIN(touched_at) AS first_touched_at, "
            f"MAX(touched_at) AS last_touched_at FROM {fq}.pipeline_write_mutex` "
            "GROUP BY mutex_name ORDER BY mutex_name\n"
            "    ''';\n"
            "  ELSE\n"
            "    SELECT 'missing_before_deployment' AS mutex_name, 0 AS rows_for_mutex, "
            "CAST(NULL AS TIMESTAMP) AS first_touched_at, CAST(NULL AS TIMESTAMP) AS last_touched_at;\n"
            "  END IF;\n"
            "END;",
        ),
    ])

    analytics = (
        ("video_metadata", "snapshot_date", "snapshot_date, video_id"),
        ("daily_video_stats", "snapshot_date", "snapshot_date, video_id"),
        ("daily_video_analytics", "activity_date", "activity_date, video_id"),
        ("daily_traffic_sources", "activity_date", "activity_date, video_id, traffic_source_type"),
    )
    analytics_parts = []
    for table, date_column, grain in analytics:
        analytics_parts.append(
            f"SELECT '{table}' AS table_name, COUNT(*) AS physical_rows, COUNT(DISTINCT {date_column}) AS partitions, "
            f"MIN({date_column}) AS first_date, MAX({date_column}) AS latest_date, "
            f"BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS whole_table_fingerprint, "
            f"(SELECT COUNT(*) FROM (SELECT 1 FROM {fq}.{table}` GROUP BY {grain} HAVING COUNT(*) > 1)) AS duplicate_groups "
            f"FROM {fq}.{table}` t"
        )
    blocks.append(_proof_block(
        "analytics_integrity", "Complete Analytics counts, coverage, fingerprints and native-grain duplicates.",
        "\nUNION ALL\n".join(analytics_parts) + "\nORDER BY table_name;",
    ))
    blocks.append(_proof_block(
        "analytics_partition_fingerprints", "Every Analytics partition count and order-independent fingerprint.",
        "SELECT 'video_metadata' AS table_name, snapshot_date AS partition_date, COUNT(*) AS physical_rows, "
        f"BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS fingerprint FROM {fq}.video_metadata` t GROUP BY snapshot_date\n"
        "UNION ALL SELECT 'daily_video_stats', snapshot_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) "
        f"FROM {fq}.daily_video_stats` t GROUP BY snapshot_date\n"
        "UNION ALL SELECT 'daily_video_analytics', activity_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) "
        f"FROM {fq}.daily_video_analytics` t GROUP BY activity_date\n"
        "UNION ALL SELECT 'daily_traffic_sources', activity_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) "
        f"FROM {fq}.daily_traffic_sources` t GROUP BY activity_date ORDER BY table_name, partition_date;",
    ))
    blocks.append(_proof_block(
        "analytics_multiple_load_sources",
        "Every Analytics native grain carrying more than one load source. Only the two activity-date tables have provenance columns.",
        "SELECT 'daily_video_analytics' AS table_name, activity_date AS partition_date, video_id, "
        f"CAST(NULL AS STRING) AS traffic_source_type, ARRAY_AGG(DISTINCT load_source ORDER BY load_source) AS load_sources "
        f"FROM {fq}.daily_video_analytics` GROUP BY activity_date, video_id HAVING COUNT(DISTINCT load_source) > 1\n"
        "UNION ALL\n"
        "SELECT 'daily_traffic_sources', activity_date, video_id, traffic_source_type, "
        f"ARRAY_AGG(DISTINCT load_source ORDER BY load_source) FROM {fq}.daily_traffic_sources` "
        "GROUP BY activity_date, video_id, traffic_source_type HAVING COUNT(DISTINCT load_source) > 1 "
        "ORDER BY table_name, partition_date, video_id, traffic_source_type;",
    ))
    blocks.append(_proof_block(
        "analytics_refresh_archive_reconciliation",
        "Every archived refresh generation compared with the current live partition by row count and canonical fingerprint.",
        "WITH archive AS ("
        "SELECT 'daily_video_analytics' AS table_name, activity_date, refresh_run_id, COUNT(*) AS archive_rows, "
        "BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING((SELECT AS STRUCT a.* EXCEPT(archived_at, refresh_run_id))))) AS archive_fingerprint "
        f"FROM {fq}.daily_video_analytics_refresh_archive` a GROUP BY activity_date, refresh_run_id "
        "UNION ALL SELECT 'daily_traffic_sources', activity_date, refresh_run_id, COUNT(*), "
        "BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING((SELECT AS STRUCT a.* EXCEPT(archived_at, refresh_run_id))))) "
        f"FROM {fq}.daily_traffic_sources_refresh_archive` a GROUP BY activity_date, refresh_run_id), "
        "live AS (SELECT 'daily_video_analytics' AS table_name, activity_date, COUNT(*) AS live_rows, "
        f"BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) AS live_fingerprint FROM {fq}.daily_video_analytics` t GROUP BY activity_date "
        "UNION ALL SELECT 'daily_traffic_sources', activity_date, COUNT(*), BIT_XOR(FARM_FINGERPRINT(TO_JSON_STRING(t))) "
        f"FROM {fq}.daily_traffic_sources` t GROUP BY activity_date) "
        "SELECT archive.table_name, archive.activity_date, archive.refresh_run_id, archive.archive_rows, live.live_rows, "
        "archive.archive_fingerprint, live.live_fingerprint, archive.archive_rows = live.live_rows AS row_count_equal, "
        "archive.archive_fingerprint = live.live_fingerprint AS fingerprint_equal "
        "FROM archive LEFT JOIN live USING (table_name, activity_date) "
        "ORDER BY table_name, activity_date, refresh_run_id;",
    ))
    traffic = f"{fq}.reporting_channel_traffic_source_a3`"
    analytics_traffic = f"{fq}.daily_traffic_sources`"
    basic = f"{fq}.reporting_channel_basic_a3`"
    analytics_video = f"{fq}.daily_video_analytics`"
    blocks.extend([
        _proof_block(
            "reconcile_views_video_day",
            "Every joined video-day across the shared window. Grain: activity date and video id. Threshold: greater of 5 views or 5 percent of Analytics views.",
            f"WITH rd AS (SELECT DISTINCT report_date AS d FROM {traffic}), ad AS (SELECT DISTINCT activity_date AS d FROM {analytics_traffic}), "
            "shared AS (SELECT d FROM rd JOIN ad USING (d)), "
            f"r AS (SELECT report_date AS d, video_id, SUM(views) AS reporting_views, SUM(engaged_views) AS reporting_engaged FROM {traffic} "
            "WHERE report_date IN (SELECT d FROM shared) AND video_id IS NOT NULL GROUP BY d, video_id), "
            f"a AS (SELECT activity_date AS d, video_id, SUM(views) AS analytics_views FROM {analytics_traffic} "
            "WHERE activity_date IN (SELECT d FROM shared) GROUP BY d, video_id HAVING analytics_views > 0) "
            "SELECT COALESCE(r.d, a.d) AS activity_date, COALESCE(r.video_id, a.video_id) AS video_id, "
            "r.reporting_views, r.reporting_engaged, a.analytics_views, ABS(IFNULL(r.reporting_views, 0) - IFNULL(a.analytics_views, 0)) AS absolute_diff, "
            "GREATEST(5, 0.05 * IFNULL(a.analytics_views, 0)) AS allowed_diff, r.d IS NULL AS analytics_only, a.d IS NULL AS reporting_only "
            "FROM r FULL OUTER JOIN a USING (d, video_id) ORDER BY activity_date, video_id;",
        ),
        _proof_block(
            "reconcile_views_channel_day",
            "Every channel-day across the shared date window with both source totals.",
            f"WITH r AS (SELECT report_date AS d, SUM(views) AS reporting_views, SUM(engaged_views) AS reporting_engaged FROM {traffic} GROUP BY d), "
            f"a AS (SELECT activity_date AS d, SUM(views) AS analytics_views FROM {analytics_traffic} GROUP BY d), "
            "win AS (SELECT MIN(d) AS lo, MAX(d) AS hi FROM (SELECT d FROM r JOIN a USING (d))) "
            "SELECT COALESCE(r.d, a.d) AS activity_date, reporting_views, reporting_engaged, analytics_views, "
            "reporting_views - analytics_views AS signed_diff, SAFE_DIVIDE(ABS(reporting_views - analytics_views), analytics_views) AS absolute_diff_share, "
            "CASE WHEN r.d IS NULL THEN 'analytics_only' WHEN a.d IS NULL THEN 'reporting_only' END AS one_sided "
            "FROM r FULL OUTER JOIN a USING (d), win WHERE COALESCE(r.d, a.d) BETWEEN win.lo AND win.hi ORDER BY activity_date;",
        ),
        _proof_block(
            "reconcile_subscribers",
            "Every video-day whose subscriber gains differ by more than one across the shared window.",
            f"WITH shared AS (SELECT d FROM (SELECT DISTINCT report_date AS d FROM {basic}) JOIN "
            f"(SELECT DISTINCT activity_date AS d FROM {analytics_video}) USING (d)), "
            f"r AS (SELECT report_date AS d, video_id, SUM(subscribers_gained) AS reporting_subscribers FROM {basic} "
            "WHERE video_id IS NOT NULL AND report_date IN (SELECT d FROM shared) GROUP BY d, video_id), "
            f"a AS (SELECT activity_date AS d, video_id, SUM(subscribers_gained) AS analytics_subscribers FROM {analytics_video} "
            "WHERE activity_date IN (SELECT d FROM shared) GROUP BY d, video_id) "
            "SELECT COALESCE(r.d, a.d) AS activity_date, COALESCE(r.video_id, a.video_id) AS video_id, reporting_subscribers, analytics_subscribers, "
            "ABS(IFNULL(reporting_subscribers, 0) - IFNULL(analytics_subscribers, 0)) AS absolute_diff "
            "FROM r FULL OUTER JOIN a USING (d, video_id) WHERE ABS(IFNULL(reporting_subscribers, 0) - IFNULL(analytics_subscribers, 0)) > 1 "
            "ORDER BY activity_date, video_id;",
        ),
        _proof_block(
            "cross_source_date_coverage",
            "Every date available in only one traffic source within the shared minimum and maximum window.",
            f"WITH r AS (SELECT DISTINCT report_date AS d FROM {traffic}), a AS (SELECT DISTINCT activity_date AS d FROM {analytics_traffic}), "
            "win AS (SELECT MIN(d) AS lo, MAX(d) AS hi FROM (SELECT d FROM r JOIN a USING (d))) "
            "SELECT COALESCE(r.d, a.d) AS activity_date, r.d IS NULL AS analytics_only, a.d IS NULL AS reporting_only "
            "FROM r FULL OUTER JOIN a USING (d), win WHERE COALESCE(r.d, a.d) BETWEEN win.lo AND win.hi AND (r.d IS NULL OR a.d IS NULL) "
            "ORDER BY activity_date;",
        ),
        _proof_block(
            "analytics_partial_days",
            "Every shared date with Reporting video rows absent from Analytics traffic. Denominator is Reporting videos with positive views.",
            f"WITH shared AS (SELECT d FROM (SELECT DISTINCT report_date AS d FROM {traffic}) JOIN "
            f"(SELECT DISTINCT activity_date AS d FROM {analytics_traffic}) USING (d)), "
            f"r AS (SELECT report_date AS d, video_id, SUM(views) AS views FROM {traffic} WHERE video_id IS NOT NULL "
            "AND report_date IN (SELECT d FROM shared) GROUP BY d, video_id HAVING views > 0), "
            f"a AS (SELECT DISTINCT activity_date AS d, video_id FROM {analytics_traffic} WHERE activity_date IN (SELECT d FROM shared)) "
            "SELECT r.d AS activity_date, COUNT(*) AS reporting_videos_missing, SUM(r.views) AS reporting_views_missing, "
            "(SELECT COUNT(*) FROM r denominator WHERE denominator.d = r.d) AS reporting_positive_view_videos "
            "FROM r LEFT JOIN a USING (d, video_id) WHERE a.video_id IS NULL GROUP BY activity_date ORDER BY activity_date;",
        ),
        _proof_block(
            "reporting_coverage_calendar",
            "Complete ledger coverage by report type and date, including every status and generation.",
            f"SELECT report_type, report_date, ARRAY_AGG(STRUCT(report_id, report_create_time, status, row_count, load_source, ingested_at, error) "
            f"ORDER BY report_create_time, ingested_at) AS generations FROM {fq}.{LEDGER_TABLE}` GROUP BY report_type, report_date "
            "ORDER BY report_type, report_date;",
        ),
        _proof_block(
            "reporting_generation_latency",
            "Generation latency in hours and regeneration counts for every report type.",
            f"SELECT report_type, APPROX_QUANTILES(TIMESTAMP_DIFF(report_create_time, TIMESTAMP(report_date, 'America/Los_Angeles'), HOUR), 4) "
            f"AS hours_quartiles, COUNT(DISTINCT report_date) AS days, COUNT(*) AS reports, COUNT(DISTINCT IF(generations > 1, report_date, NULL)) "
            f"AS regenerated_days FROM (SELECT *, COUNT(*) OVER (PARTITION BY job_id, report_date) AS generations FROM {fq}.{LEDGER_TABLE}`) "
            "GROUP BY report_type ORDER BY report_type;",
        ),
        _proof_block(
            "traffic_anonymization",
            "Traffic detail null and anonymization shares. Denominator is every physical traffic row.",
            f"SELECT COUNT(*) AS denominator_rows, COUNTIF(video_id IS NULL) AS video_id_null_rows, "
            "SAFE_DIVIDE(COUNTIF(video_id IS NULL), COUNT(*)) AS video_id_null_share, COUNTIF(traffic_source_detail IS NULL) AS detail_null_rows, "
            "SAFE_DIVIDE(COUNTIF(traffic_source_detail IS NULL), COUNT(*)) AS detail_null_share, COUNTIF(country_code = 'ZZ') AS country_zz_rows, "
            f"SAFE_DIVIDE(COUNTIF(country_code = 'ZZ'), COUNT(*)) AS country_zz_share FROM {traffic};",
        ),
    ])
    return (
        "-- Production proof pack. GENERATED by setup/generate_reporting_ddl.py from\n"
        "-- cloud_function/report_specs.py. Every query is read-only and has no row cap.\n"
        "-- Replace PROJECT_ID, BQ_DATASET and AFFECTED_DATE placeholders before execution.\n\n"
        + "".join(blocks)
    ).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text, checks, proof = render(), render_checks(), render_proof()
    if args.check:
        stale = [str(f) for f, want in ((OUT, text), (CHECKS_OUT, checks), (PROOF_OUT, proof))
                 if (f.read_text() if f.exists() else "") != want]
        if stale:
            print(f"out of date: {', '.join(stale)}; run {Path(__file__).name}", file=sys.stderr)
            return 1
        print("DDL, structural checks and proof pack match specs")
        return 0
    OUT.write_text(text)
    CHECKS_OUT.write_text(checks)
    PROOF_OUT.write_text(proof)
    print(f"wrote {OUT} ({len(SPECS)} tables + ledger), {CHECKS_OUT} and {PROOF_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
