-- YouTube Reporting API raw tables. GENERATED by setup/generate_reporting_ddl.py from
-- cloud_function/report_specs.py. Do not edit by hand; edit the specs and re-run.
--
-- One table per report type at the report's native grain (one row per combination of
-- its dimensions per Pacific day). Dimension values can be NULL: channel_basic_a3 emits a
-- channel-level row with no video_id, and detail dimensions are blank under YouTube's
-- anonymisation threshold. report_date is the report day; the idempotency key is the
-- whole report_date partition, replaced atomically when a newer generation of the same
-- day arrives. Provenance columns say which report file each row came from.
--
-- Ratios (ctr, *_rate, *_percentage) are per-row averages and are never summed; recompute
-- from totals. Timezone: report_date is a Pacific-time day, the same convention as the
-- Analytics API's activity_date.


-- One row per report file YouTube has generated. Every status transition is a MERGE
-- keyed on report_id. status: loaded | header_only | header_only_conflict | superseded |
-- skipped_older | failed. gcs_uri points at the archived copy; content_sha256 is the
-- CSV body's hash before compression.
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_ingest_ledger` (
    report_id STRING NOT NULL,
    job_id STRING NOT NULL,
    report_type STRING NOT NULL,
    report_date DATE NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    status STRING NOT NULL,
    row_count INT64,
    csv_bytes INT64,
    content_sha256 STRING,
    gcs_uri STRING,
    load_source STRING,
    ingested_at TIMESTAMP NOT NULL,
    error STRING
)
CLUSTER BY job_id, report_date
OPTIONS (
    description = 'Ingest ledger for YouTube Reporting API report files. One row per report_id; drives what to load and proves newest-createTime-wins.'
);

-- channel_basic_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_basic_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    engaged_views INT64,
    views INT64,
    comments INT64,
    likes INT64,
    dislikes INT64,
    videos_added_to_playlists INT64,
    videos_removed_from_playlists INT64,
    shares INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    annotation_click_through_rate FLOAT64,
    annotation_close_rate FLOAT64,
    annotation_impressions INT64,
    annotation_clickable_impressions INT64,
    annotation_closable_impressions INT64,
    annotation_clicks INT64,
    annotation_closes INT64,
    card_click_rate FLOAT64,
    card_teaser_click_rate FLOAT64,
    card_impressions INT64,
    card_teaser_impressions INT64,
    card_clicks INT64,
    card_teaser_clicks INT64,
    subscribers_gained INT64,
    subscribers_lost INT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_basic_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_province_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_province_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    province_code STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    annotation_click_through_rate FLOAT64,
    annotation_close_rate FLOAT64,
    annotation_impressions INT64,
    annotation_clickable_impressions INT64,
    annotation_closable_impressions INT64,
    annotation_clicks INT64,
    annotation_closes INT64,
    card_click_rate FLOAT64,
    card_teaser_click_rate FLOAT64,
    card_impressions INT64,
    card_teaser_impressions INT64,
    card_clicks INT64,
    card_teaser_clicks INT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_province_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_playback_location_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_playback_location_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    playback_location_type STRING,
    playback_location_detail STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_playback_location_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_traffic_source_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_traffic_source_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    traffic_source_type STRING,
    traffic_source_detail STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_traffic_source_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_device_os_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_device_os_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    device_type STRING,
    operating_system STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_device_os_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_subtitles_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, subtitle_language, subtitle_language_autotranslated)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_subtitles_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    subtitle_language STRING,
    subtitle_language_autotranslated STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_subtitles_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, subtitle_language, subtitle_language_autotranslated. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_combined_a3: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_combined_a3` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    playback_location_type STRING,
    traffic_source_type STRING,
    device_type STRING,
    operating_system STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    average_view_duration_percentage FLOAT64,
    red_views INT64,
    red_watch_time_minutes FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_combined_a3. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_demographics_a1: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, age_group, gender)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_demographics_a1` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    age_group STRING,
    gender STRING,
    views_percentage FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_demographics_a1. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, age_group, gender. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_sharing_service_a1: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, sharing_service)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_sharing_service_a1` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    sharing_service STRING,
    shares INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_sharing_service_a1. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, sharing_service. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_cards_a1: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, card_type, card_id)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_cards_a1` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    card_type STRING,
    card_id STRING,
    card_click_rate FLOAT64,
    card_teaser_click_rate FLOAT64,
    card_impressions INT64,
    card_teaser_impressions INT64,
    card_clicks INT64,
    card_teaser_clicks INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_cards_a1. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, card_type, card_id. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_end_screens_a1: grain (report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, end_screen_element_type, end_screen_element_id)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_end_screens_a1` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    end_screen_element_type STRING,
    end_screen_element_id STRING,
    end_screen_element_clicks INT64,
    end_screen_element_impressions INT64,
    end_screen_element_click_rate FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_end_screens_a1. Grain: report_date, channel_id, video_id, live_or_on_demand, subscribed_status, country_code, end_screen_element_type, end_screen_element_id. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_reach_basic_a1: grain (report_date, channel_id, video_id)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_reach_basic_a1` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    video_thumbnail_impressions INT64,
    video_thumbnail_impressions_ctr FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_reach_basic_a1. Grain: report_date, channel_id, video_id. Partition = report_date (Pacific day); one report_id per partition.'
);

-- channel_reach_combined_a1: grain (report_date, channel_id, video_id, traffic_source_type, traffic_source_detail, operating_system, device_type)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_channel_reach_combined_a1` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    video_id STRING,
    traffic_source_type STRING,
    traffic_source_detail STRING,
    operating_system STRING,
    device_type STRING,
    video_thumbnail_impressions INT64,
    video_thumbnail_impressions_ctr FLOAT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API channel_reach_combined_a1. Grain: report_date, channel_id, video_id, traffic_source_type, traffic_source_detail, operating_system, device_type. Partition = report_date (Pacific day); one report_id per partition.'
);

-- playlist_basic_a2: grain (report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_playlist_basic_a2` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    playlist_id STRING,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    playlist_starts INT64,
    playlist_saves_added INT64,
    playlist_saves_removed INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API playlist_basic_a2. Grain: report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code. Partition = report_date (Pacific day); one report_id per partition.'
);

-- playlist_province_a2: grain (report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_playlist_province_a2` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    playlist_id STRING,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    province_code STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    playlist_starts INT64,
    playlist_saves_added INT64,
    playlist_saves_removed INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API playlist_province_a2. Grain: report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, province_code. Partition = report_date (Pacific day); one report_id per partition.'
);

-- playlist_playback_location_a2: grain (report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_playlist_playback_location_a2` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    playlist_id STRING,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    playback_location_type STRING,
    playback_location_detail STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    playlist_starts INT64,
    playlist_saves_added INT64,
    playlist_saves_removed INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API playlist_playback_location_a2. Grain: report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, playback_location_detail. Partition = report_date (Pacific day); one report_id per partition.'
);

-- playlist_traffic_source_a2: grain (report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_playlist_traffic_source_a2` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    playlist_id STRING,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    traffic_source_type STRING,
    traffic_source_detail STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    playlist_starts INT64,
    playlist_saves_added INT64,
    playlist_saves_removed INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API playlist_traffic_source_a2. Grain: report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, traffic_source_type, traffic_source_detail. Partition = report_date (Pacific day); one report_id per partition.'
);

-- playlist_device_os_a2: grain (report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_playlist_device_os_a2` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    playlist_id STRING,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    device_type STRING,
    operating_system STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    playlist_starts INT64,
    playlist_saves_added INT64,
    playlist_saves_removed INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API playlist_device_os_a2. Grain: report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, device_type, operating_system. Partition = report_date (Pacific day); one report_id per partition.'
);

-- playlist_combined_a2: grain (report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system)
CREATE TABLE IF NOT EXISTS `${BQ_DATASET}.reporting_playlist_combined_a2` (
    report_date DATE NOT NULL,
    channel_id STRING NOT NULL,
    playlist_id STRING,
    video_id STRING,
    live_or_on_demand STRING,
    subscribed_status STRING,
    country_code STRING,
    playback_location_type STRING,
    traffic_source_type STRING,
    device_type STRING,
    operating_system STRING,
    engaged_views INT64,
    views INT64,
    watch_time_minutes FLOAT64,
    average_view_duration_seconds FLOAT64,
    playlist_starts INT64,
    playlist_saves_added INT64,
    playlist_saves_removed INT64,
    report_id STRING NOT NULL,
    report_create_time TIMESTAMP NOT NULL,
    job_id STRING NOT NULL,
    load_source STRING NOT NULL,
    ingested_at TIMESTAMP NOT NULL
)
PARTITION BY report_date
CLUSTER BY video_id
OPTIONS (
    description = 'Raw YouTube Reporting API playlist_combined_a2. Grain: report_date, channel_id, playlist_id, video_id, live_or_on_demand, subscribed_status, country_code, playback_location_type, traffic_source_type, device_type, operating_system. Partition = report_date (Pacific day); one report_id per partition.'
);
